[project]
name = "gold-price-pipeline"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kafka-python>=2.3.0",
    "pyspark>=4.1.0",
    "scrapy>=2.13.4",
    "yfinance>=1.0",
]
